#!/usr/bin/env python3
"""RFC Phase 2 (F5/F14): generate docs/blocks-index.md — the DERIVED reverse index.

For each block, a table of `recipe x envelope x measured-Gate-B x status`,
generated on demand from recipes. `used_by` is NEVER a stored field (F14: stored
per-block lists reintroduce the PR #25-28 merge-collision class). Generation is
the fix: two in-flight registrations of SigLIP-bearing models never collide on
shared lines.

Honest status vocabulary (F1/F12): reports `measured @ {envelope}`, NEVER
`SOLVED`. A block "known" at one envelope tuple `(graph, static shape,
precision, host-contract)` carries NO promise at another. Loadability is never
inferred from block facts.

Usage:
    python scripts/generate_blocks_index.py            # writes docs/blocks-index.md
    python scripts/generate_blocks_index.py --check    # exit 1 if out of date
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from coreai_fabric.convert import converter_stack_versions  # noqa: E402
from coreai_fabric.recipes import load_all_recipes  # noqa: E402
from coreai_fabric.util import read_yaml, today  # noqa: E402

OUT = REPO_ROOT / "docs" / "blocks-index.md"
VOCAB = REPO_ROOT / "schema" / "blocks-vocab.yaml"


def _block_usage(recipes) -> dict[str, list[dict]]:
    """block_id -> [{recipe, envelope, status, measured}] derived from recipes.
    Never stored; generated each run (F14)."""
    usage: dict[str, list[dict]] = {}
    for r in recipes:
        blocks = (r.data.get("catalog") or {}).get("blocks") or []
        if not isinstance(blocks, list):
            continue
        conv = r.data.get("conversion", {})
        envelope = {
            "precision": conv.get("precision"),
            "quantization": conv.get("quantization"),
        }
        graphs = (conv.get("action") or {}).get("graphs")
        if isinstance(graphs, list) and graphs:
            envelope["graphs"] = [str(g.get("name", "")) for g in graphs if isinstance(g, dict)]
        proto = ((r.data.get("parity") or {}).get("gate_b") or {}).get("protocol") or {}
        measured = None
        if proto:
            measured = "measured"
        for bid in blocks:
            if isinstance(bid, str):
                usage.setdefault(bid, []).append({
                    "recipe": r.id,
                    "status": r.data.get("status"),
                    "envelope": envelope,
                    "measured": measured,
                    "protocol": proto,
                })
    return usage


def _envelope_str(env: dict) -> str:
    parts = []
    if env.get("precision"):
        parts.append(str(env["precision"]))
    if env.get("quantization") and env["quantization"] != "none":
        parts.append(str(env["quantization"]))
    if env.get("graphs"):
        parts.append("/".join(env["graphs"]))
    return ", ".join(parts) or "default"


def _orphaned_blocks(recipes, vocab_ids: set[str]) -> list[str]:
    """F15: block ids referenced by recipes but missing from the vocab — a rename
    can't silently orphan the index."""
    referenced: set[str] = set()
    for r in recipes:
        for bid in (r.data.get("catalog") or {}).get("blocks") or []:
            if isinstance(bid, str):
                referenced.add(bid)
    return sorted(referenced - vocab_ids)


def generate() -> tuple[str, list[str]]:
    recipes = load_all_recipes(REPO_ROOT)
    vocab = read_yaml(VOCAB) if VOCAB.is_file() else {"blocks": []}
    vocab_blocks = vocab.get("blocks", []) if isinstance(vocab, dict) else []
    vocab_ids = {str(b.get("id")) for b in vocab_blocks if isinstance(b, dict) and b.get("id")}
    usage = _block_usage(recipes)
    orphans = _orphaned_blocks(recipes, vocab_ids)
    stack = converter_stack_versions()
    stack_str = ", ".join(f"{k}=={v}" for k, v in sorted(stack.items())) or "unknown"

    lines = [
        "# Blocks index — derived reverse index (GENERATED)",
        "",
        "<!-- RFC Phase 2 (F5/F14): GENERATED by scripts/generate_blocks_index.py. "
        "Do not edit; `used_by` is derived, never stored. -->",
        "",
        f"- **verified_at:** {today()}",
        f"- **toolchain_version:** {stack_str}",
        "",
        "## How to read this (F1/F12)",
        "",
        "A block is an ARCHITECTURE id only — no license of its own (license stays "
        "per-recipe). **Loadability is never inferred from a block id**: a block "
        "'known' at one envelope `(graph, static shape, precision, host-contract)` "
        "carries NO promise at another (the same MoE stack loads at L=12 fp16, "
        "fails at L=18). Status reports **`measured @ {envelope}`** — NEVER `SOLVED`. "
        "SenseNova's SigLIP @ 980px/patch-14 in a MoT is NET-NEW, not covered by a "
        "lingbot ViT-B/16 @ 512px.",
        "",
    ]

    if orphans:
        lines.append("## ⚠ Orphaned block references (F15)")
        lines.append("")
        for o in orphans:
            lines.append(f"- `{o}` is referenced by a recipe but is NOT in "
                         f"`schema/blocks-vocab.yaml` — add it or fix the reference.")
        lines.append("")

    # Vocab blocks in declared order, then any used-but-undeclared (already warned).
    for vb in vocab_blocks:
        if not isinstance(vb, dict):
            continue
        bid = str(vb.get("id", ""))
        if not bid:
            continue
        desc = vb.get("description", "")
        uses = usage.get(bid, [])
        lines.append(f"## `{bid}`")
        lines.append(f"_{desc}_")
        lines.append("")
        if not uses:
            lines.append("_(no recipe composes this block yet — a vocab entry ahead of use.)_")
            lines.append("")
            continue
        lines.append("| recipe | envelope | status | measured-Gate-B |")
        lines.append("|--------|----------|--------|-----------------|")
        for u in sorted(uses, key=lambda x: x["recipe"]):
            proto = u["protocol"]
            if proto:
                meas = (f"measured @ {_envelope_str(u['envelope'])} "
                        f"({proto.get('metric', '?')}, n_obs={proto.get('n_obs', '?')})")
            else:
                meas = "—"
            lines.append(f"| {u['recipe']} | {_envelope_str(u['envelope'])} | {u['status']} | {meas} |")
        lines.append("")

    return "\n".join(lines) + "\n", orphans


def _content(text: str) -> str:
    """Comparable body, excluding the env-specific freshness header lines so
    --check is a real committed-vs-fresh guard (F14) that is stable across
    toolchain environments (F15)."""
    skip = ("- **verified_at:**", "- **toolchain_version:**")
    return "\n".join(l for l in text.splitlines() if not l.startswith(skip)).strip()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if docs/blocks-index.md is out of date (CI guard)")
    args = parser.parse_args(argv)

    text, orphans = generate()
    if args.check:
        current = OUT.read_text() if OUT.is_file() else ""
        if _content(current) != _content(text):
            print("docs/blocks-index.md is out of date — run: python scripts/generate_blocks_index.py",
                  file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO_ROOT)} ({len(text)} bytes)")
    if orphans:
        print(f"WARNING: {len(orphans)} orphaned block reference(s): {', '.join(orphans)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
