#!/usr/bin/env python3
"""RFC Phase 0e (F2/F6): generate docs/scorecard.md — the per-cell SotA table.

"The Gate-B number" is several incommensurable quantities (match-rate vs cosine,
per-row vs flattened, synthetic vs recorded, fp16 vs fp32). Ranking across them
crowns the weakest verification (F2). So rankings exist ONLY within a
`(metric, granularity, input_protocol, reference_dtype, graph_boundary)` cell,
on raw values, with waiver flags shown. There is no cross-cell "best".

This is the honestly-reduced Layer D. It supersedes the hand-built playbook §7
table (which stays as the prototype this was generated from). Deterministic:
a test asserts the output is reproducible from the recipes.

Usage:
    python scripts/generate_scorecard.py            # writes docs/scorecard.md
    python scripts/generate_scorecard.py --check    # exit 1 if out of date
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from coreai_fabric.convert import converter_stack_versions  # noqa: E402
from coreai_fabric.recipes import load_all_recipes  # noqa: E402
from coreai_fabric.util import today  # noqa: E402
from coreai_fabric.verify import METRIC_GRANULARITY, parity_report_path  # noqa: E402

OUT = REPO_ROOT / "docs" / "scorecard.md"


def _row_for(recipe) -> dict | None:
    """One scorecard row from a recipe + its committed parity report, or None
    when the recipe has no measured Gate-B number to rank."""
    gb_recipe = (recipe.data.get("parity") or {}).get("gate_b") or {}
    metric = gb_recipe.get("metric")
    if not metric:
        return None
    # The durable measured result + protocol signature live in the RECIPE (written
    # by verify, RFC F6) so the scorecard reproduces on a fresh clone. A fresher
    # build/<id>/parity-report.json, when present, is preferred.
    measured = gb_recipe.get("measured") or {}
    proto = gb_recipe.get("protocol") or {}
    value = measured.get("value")
    n_obs = measured.get("n_obs") or proto.get("n_obs")
    rpath = parity_report_path(REPO_ROOT, recipe)
    if rpath.is_file():
        import json
        try:
            rep = json.loads(rpath.read_text())
            gbr = rep.get("gate_b", {})
            if isinstance(gbr.get("value"), (int, float)):
                value = gbr["value"]
            if isinstance(gbr.get("n_obs"), int):
                n_obs = gbr["n_obs"]
        except (ValueError, OSError):
            pass
    # A row is rankable only with a measured value AND a protocol signature.
    if value is None or not proto:
        return None
    return {
        "recipe": recipe.id,
        "metric": metric,
        "value": value,
        "n_obs": n_obs,
        "status": recipe.data.get("status"),
        "precision": (recipe.data.get("conversion") or {}).get("precision"),
        "granularity": proto.get("granularity") or METRIC_GRANULARITY.get(metric, "?"),
        "input_protocol": proto.get("input_protocol", "?"),
        "reference_dtype": proto.get("reference_dtype", "?"),
        "graph_boundary": proto.get("graph_boundary", "?"),
        "waivers": proto.get("waivers") or [],
    }


def _cell_key(row: dict) -> tuple:
    return (row["metric"], row["granularity"], row["input_protocol"],
            row["reference_dtype"], row["graph_boundary"])


def _fmt_value(v: float) -> str:
    # Cosines cluster near 1.0 — show enough digits to distinguish 0.99948 from 0.99999.
    return f"{v:.6f}".rstrip("0").rstrip(".")


def generate() -> str:
    rows = [r for r in (_row_for(rcp) for rcp in load_all_recipes(REPO_ROOT)) if r]
    stack = converter_stack_versions()
    stack_str = ", ".join(f"{k}=={v}" for k, v in sorted(stack.items())) or "unknown"

    lines = [
        "# Scorecard — measured Gate-B parity (GENERATED)",
        "",
        "<!-- RFC Phase 0 (F2/F6): GENERATED by scripts/generate_scorecard.py. "
        "Do not edit by hand; regenerate with `python scripts/generate_scorecard.py`. -->",
        "",
        f"- **verified_at:** {today()}",
        f"- **toolchain_version:** {stack_str}",
        "",
        "## How to read this (the F2 rule)",
        "",
        "**Rankings exist only WITHIN a cell** `(metric, granularity, "
        "input_protocol, reference_dtype, graph_boundary)`, on raw values. There "
        "is **no cross-cell 'best'** — a flattened 1600-dim cosine is not "
        "comparable to a per-row 14-dim min, and a synthetic-input number is not "
        "comparable to a recorded-dataset one (the smolvla 0.02-cosine catastrophe "
        "is why `input_protocol` is recorded). A 🚩 marks a waivered pass "
        "(e.g. near-zero-action conditioning) — surfaced, never hidden.",
        "",
        "Cells with a single entry are listed but not ranked. Absent recipes are "
        "either unmeasured (Gate B not_run) or carry no protocol signature yet.",
        "",
    ]

    if not rows:
        lines += ["_(no recipes carry a measured Gate-B value + protocol signature yet — "
                  "run `coreai-fabric verify` to populate one.)_", ""]
        return "\n".join(lines)

    # Group by cell, rank within cell by raw value desc.
    cells: dict[tuple, list[dict]] = {}
    for row in rows:
        cells.setdefault(_cell_key(row), []).append(row)

    for cell in sorted(cells):
        metric, gran, inp, rdt, boundary = cell
        members = sorted(cells[cell], key=lambda r: r["value"], reverse=True)
        lines.append(f"### Cell: `{metric}` · {gran} · {inp} · {rdt}")
        lines.append(f"_{boundary}_")
        lines.append("")
        lines.append("| # | recipe | value | n_obs | precision | status | waivers |")
        lines.append("|---|--------|-------|-------|-----------|--------|---------|")
        for i, r in enumerate(members, 1):
            w = " ".join(f"🚩{x}" for x in r["waivers"])
            lines.append(
                f"| {i} | {r['recipe']} | {_fmt_value(r['value'])} | "
                f"{r['n_obs'] or '?'} | {r['precision']} | {r['status']} | {w} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


def _content(text: str) -> str:
    """The comparable body, excluding the env-specific freshness header lines
    (verified_at / toolchain_version). This makes --check a REAL committed-vs-fresh
    content guard (F14) that is stable across toolchain environments (F15) — before,
    the stamp made --check fail on any machine but the author's, and the tests
    overwrote-then-checked (a tautology that never guarded committed drift)."""
    skip = ("- **verified_at:**", "- **toolchain_version:**")
    return "\n".join(l for l in text.splitlines() if not l.startswith(skip)).strip()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if docs/scorecard.md is out of date (CI guard)")
    args = parser.parse_args(argv)

    text = generate()
    if args.check:
        current = OUT.read_text() if OUT.is_file() else ""
        if _content(current) != _content(text):
            print("docs/scorecard.md is out of date — run: python scripts/generate_scorecard.py",
                  file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO_ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
